[project]
name = "jarvis-ironman"
dynamic = ["version"]
description = "Voice-Activated Natural Language UI"
readme = "README.md"
authors = [{ name = "Vignesh Rao", email = "svignesh1793@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Information Technology",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Home Automation",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: System :: Hardware :: Universal Serial Bus (USB) :: Wireless Controller",
    "Topic :: Multimedia :: Sound/Audio :: Conversion",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Hardware :: Hardware Drivers",
    "Topic :: System :: Hardware :: Symmetric Multi-processing",
    "Framework :: AnyIO",
    "Framework :: FastAPI",
    "Framework :: AsyncIO",
    "Framework :: Pydantic :: 2",
    "Framework :: Setuptools Plugin",
    "Framework :: aiohttp",
    "Natural Language :: English"
]
keywords = ["python", "home-automation", "natural-language-processing", "text-to-speech",
            "speech-recognition", "jarvis", "hotword-detection", "virtual-assistant"]
requires-python = ">=3.10,<3.12"  # Only 3.10 and 3.11 are supported
dependencies = [
    "aiohttp>=3.12.13",
    "boto3>=1.39.0",
    "cryptography>=45.0.4",
    "fastapi>=0.115.14",
    "geocoder>=1.38.1",
    "google-api-python-client>=2.174.0",
    "google-auth>=2.40.3",
    "google-auth-oauthlib>=1.2.2",
    "holidays>=0.75",
    "icalendar>=6.3.1",
    "jinja2>=3.1.6",
    "jlrpy>=1.7.1",
    "matplotlib>=3.10.3",
    "newsapi-python>=0.2.7",
    "numpy>=2.2.6",
    "openai>=1.93.0",
    "opencv-python>=4.11.0.86",
    "packaging>=25.0",
    "passlib>=1.7.4",
    "psutil>=7.0.0",
    "pvporcupine>=3.0.5",
    "pydantic-settings>=2.10.1",
    "pydantic>=2.11.7",
    "pymongo>=4.13.2",
    "python-dotenv>=1.1.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.20",
    "python-telegram-bot>=22.2",
    "pyttsx3>=2.98",
    "pytz>=2025.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "sounddevice>=0.5.2",
    "speechrecognition>=3.14.3",
    "speedtest-cli>=2.1.3",
    "timezonefinder>=6.5.9",
    "toml>=0.10.2",
    "uvicorn>=0.35.0",
    "webcolors>=24.11.1",
    "websockets>=15.0.1",
    "webull>=0.6.1",
    "yfinance>=0.2.64",
    "pyhtcc>=0.1.57",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.41",
]

[tool.setuptools]
# packages section includes the directories with ONLY '.py' modules
packages     = ["jarvis", "jarvis._preexec", "jarvis.executors"]
script-files = [
    "jarvis/lib/install_darwin.sh",
    "jarvis/lib/install_linux.sh",
    "jarvis/lib/install_windows.sh",
]

[tool.setuptools.dynamic]
version      = {attr = "jarvis.version"}

[project.scripts]
# sends all the args to commandline function, where the arbitary commands as processed accordingly
jarvis = "jarvis:commandline"

[build-system]
requires      = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["sphinx==5.1.1", "pre-commit", "recommonmark", "pytest", "gitverse"]

[project.urls]
API             = "https://jarvis.vigneshrao.com"
Health          = "https://jarvis-health.vigneshrao.com"
Homepage        = "https://github.com/thevickypedia/Jarvis"
Docs            = "https://jarvis-docs.vigneshrao.com"
Demo            = "https://vigneshrao.com/Jarvis/Jarvis_Demo.mp4"
Source          = "https://github.com/thevickypedia/Jarvis"
"Bug Tracker"   = "https://github.com/thevickypedia/Jarvis/issues"
"Release Notes" = "https://github.com/thevickypedia/Jarvis/blob/master/release_notes.rst"
