[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.13",
    "fastapi>=0.115.14",
    "google-api-python-client>=2.174.0",
    "google-auth>=2.40.3",
    "google-auth-oauthlib>=1.2.2",
    "jinja2>=3.1.6",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "openai>=1.93.0",
    "opencv-python>=4.11.0.86",
    "passlib>=1.7.4",
    "psutil>=7.0.0",
    "pvporcupine>=3.0.5",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.20",
    "python-telegram-bot>=22.2",
    "pyttsx3>=2.98",
    "requests>=2.32.4",
    "sounddevice>=0.5.2",
    "speechrecognition>=3.14.3",
    "uvicorn>=0.35.0",
    "websockets>=15.0.1",
    "yfinance>=0.2.64",
]
